[package]
name = "drophost"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
log = "0.4.17"
nix = "0.26.2"
pretty_env_logger = "0.4.0"
oping = { version = "0.4.0", optional = true }
iprange = { version = "0.6.7", optional = true }
network-interface = { version = "0.1.6", optional = true }
ipnet = { version = "2.7.1", optional = true }
proc_macros = { path = "src/proc_macros" }
tokio = { version = "1.24.2", features = ["macros", "rt", "rt-multi-thread"] }
notify = "5.0.0"
once_cell = "1.17.0"

[features]
default = ["ping"]
ping = ["dep:oping"]
range = ["dep:iprange", "dep:network-interface", "dep:ipnet"]
interface = ["dep:network-interface"]

[dev-dependencies]
compile_msg = "0.1.5"
