[package]
name = "drophost"
version = "0.2.9"
edition = "2021"
license = "MIT"
description = "A simple drop-in based /etc/hosts manager"
readme = "readme.md"
authors = ["Kodi Craft <kodi@kdcf.me>"]
repository = "https://github.com/KodiCraft/drophost"
keywords = ["hosts", "drop-in", "dns", "networking"]
categories = ["network-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
log = "0.4.17"
nix = "0.26.2"
oping = { version = "0.4.0", optional = true }
iprange = { version = "0.6.7", optional = true }
network-interface = { version = "1.0.0", optional = true }
ipnet = { version = "2.7.1", optional = true }
tokio = { version = "1.27.0", features = ["macros", "rt", "rt-multi-thread"] }
notify = "5.1.0"
once_cell = "1.17.1"
env_logger = "0.10.0"

[features]
default = []
ping = ["dep:oping"]
range = ["dep:iprange", "dep:network-interface", "dep:ipnet"]
interface = ["dep:network-interface"]

[dev-dependencies]
compile_warning = { path = "compile_warning", version = "0.1.0" }