name: Build & Test on push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules 
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2.2.0
    - name: Build
      run: cargo +nightly build -r
    - name: Run tests
      run: cargo +nightly test
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: build
        # A file, directory or wildcard pattern that describes what to upload
        path: target/release/
        # The desired behavior if no files are found using the provided path.
